language: go

stages:
  - diff
  - test

go:
  - 1.12.x
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip
  include:
    - stage: diff
      go: 1.12.x
      script: diff -u <(echo -n) <(gofmt -d -s .)

script:
  - go get github.com/Wessie/appdirs
  - go get github.com/spf13/cobra
  - go get github.com/xkortex/vprint
  - go build -o $GOPATH/bin/kv
  - $GOPATH/bin/kv -h
  - go test -race -v $(go list ./... )
  - go vet ./...

